/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GamesAviatorRouteImport } from './routes/games.aviator'
import { Route as GamesDoubleRouteImport } from './routes/games.double'
import { Route as GamesFortuneTigerRouteImport } from './routes/games.fortune-tiger'
import { Route as GamesGatesOfOlympusRouteImport } from './routes/games.gates-of-olympus'
import { Route as GamesMinesRouteImport } from './routes/games.mines'
import { Route as GamesPenaltyLuckyRouteImport } from './routes/games.penalty-lucky'
import { Route as GamesPlinkoRouteImport } from './routes/games.plinko'
import { Route as GamesSweetCandyRouteImport } from './routes/games.sweet-candy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAviatorRoute = GamesAviatorRouteImport.update({
  id: '/games/aviator',
  path: '/games/aviator',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDoubleRoute = GamesDoubleRouteImport.update({
  id: '/games/double',
  path: '/games/double',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesFortuneTigerRoute = GamesFortuneTigerRouteImport.update({
  id: '/games/fortune-tiger',
  path: '/games/fortune-tiger',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGatesOfOlympusRoute = GamesGatesOfOlympusRouteImport.update({
  id: '/games/gates-of-olympus',
  path: '/games/gates-of-olympus',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMinesRoute = GamesMinesRouteImport.update({
  id: '/games/mines',
  path: '/games/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPenaltyLuckyRoute = GamesPenaltyLuckyRouteImport.update({
  id: '/games/penalty-lucky',
  path: '/games/penalty-lucky',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPlinkoRoute = GamesPlinkoRouteImport.update({
  id: '/games/plinko',
  path: '/games/plinko',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSweetCandyRoute = GamesSweetCandyRouteImport.update({
  id: '/games/sweet-candy',
  path: '/games/sweet-candy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/games/aviator': typeof GamesAviatorRoute
  '/games/double': typeof GamesDoubleRoute
  '/games/fortune-tiger': typeof GamesFortuneTigerRoute
  '/games/gates-of-olympus': typeof GamesGatesOfOlympusRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/penalty-lucky': typeof GamesPenaltyLuckyRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/sweet-candy': typeof GamesSweetCandyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/games/aviator': typeof GamesAviatorRoute
  '/games/double': typeof GamesDoubleRoute
  '/games/fortune-tiger': typeof GamesFortuneTigerRoute
  '/games/gates-of-olympus': typeof GamesGatesOfOlympusRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/penalty-lucky': typeof GamesPenaltyLuckyRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/sweet-candy': typeof GamesSweetCandyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/games/aviator': typeof GamesAviatorRoute
  '/games/double': typeof GamesDoubleRoute
  '/games/fortune-tiger': typeof GamesFortuneTigerRoute
  '/games/gates-of-olympus': typeof GamesGatesOfOlympusRoute
  '/games/mines': typeof GamesMinesRoute
  '/games/penalty-lucky': typeof GamesPenaltyLuckyRoute
  '/games/plinko': typeof GamesPlinkoRoute
  '/games/sweet-candy': typeof GamesSweetCandyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/games/aviator'
    | '/games/double'
    | '/games/fortune-tiger'
    | '/games/gates-of-olympus'
    | '/games/mines'
    | '/games/penalty-lucky'
    | '/games/plinko'
    | '/games/sweet-candy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/games/aviator'
    | '/games/double'
    | '/games/fortune-tiger'
    | '/games/gates-of-olympus'
    | '/games/mines'
    | '/games/penalty-lucky'
    | '/games/plinko'
    | '/games/sweet-candy'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/games/aviator'
    | '/games/double'
    | '/games/fortune-tiger'
    | '/games/gates-of-olympus'
    | '/games/mines'
    | '/games/penalty-lucky'
    | '/games/plinko'
    | '/games/sweet-candy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GamesAviatorRoute: typeof GamesAviatorRoute
  GamesDoubleRoute: typeof GamesDoubleRoute
  GamesFortuneTigerRoute: typeof GamesFortuneTigerRoute
  GamesGatesOfOlympusRoute: typeof GamesGatesOfOlympusRoute
  GamesMinesRoute: typeof GamesMinesRoute
  GamesPenaltyLuckyRoute: typeof GamesPenaltyLuckyRoute
  GamesPlinkoRoute: typeof GamesPlinkoRoute
  GamesSweetCandyRoute: typeof GamesSweetCandyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/aviator': {
      id: '/games/aviator'
      path: '/games/aviator'
      fullPath: '/games/aviator'
      preLoaderRoute: typeof GamesAviatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/double': {
      id: '/games/double'
      path: '/games/double'
      fullPath: '/games/double'
      preLoaderRoute: typeof GamesDoubleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/fortune-tiger': {
      id: '/games/fortune-tiger'
      path: '/games/fortune-tiger'
      fullPath: '/games/fortune-tiger'
      preLoaderRoute: typeof GamesFortuneTigerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/gates-of-olympus': {
      id: '/games/gates-of-olympus'
      path: '/games/gates-of-olympus'
      fullPath: '/games/gates-of-olympus'
      preLoaderRoute: typeof GamesGatesOfOlympusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/mines': {
      id: '/games/mines'
      path: '/games/mines'
      fullPath: '/games/mines'
      preLoaderRoute: typeof GamesMinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/penalty-lucky': {
      id: '/games/penalty-lucky'
      path: '/games/penalty-lucky'
      fullPath: '/games/penalty-lucky'
      preLoaderRoute: typeof GamesPenaltyLuckyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/plinko': {
      id: '/games/plinko'
      path: '/games/plinko'
      fullPath: '/games/plinko'
      preLoaderRoute: typeof GamesPlinkoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sweet-candy': {
      id: '/games/sweet-candy'
      path: '/games/sweet-candy'
      fullPath: '/games/sweet-candy'
      preLoaderRoute: typeof GamesSweetCandyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GamesAviatorRoute: GamesAviatorRoute,
  GamesDoubleRoute: GamesDoubleRoute,
  GamesFortuneTigerRoute: GamesFortuneTigerRoute,
  GamesGatesOfOlympusRoute: GamesGatesOfOlympusRoute,
  GamesMinesRoute: GamesMinesRoute,
  GamesPenaltyLuckyRoute: GamesPenaltyLuckyRoute,
  GamesPlinkoRoute: GamesPlinkoRoute,
  GamesSweetCandyRoute: GamesSweetCandyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
